# http://www.labri.fr/perso/nrougier/teaching/numpy.100/

## Practice numpy 100 Q's




In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.__config__.show()


1.10.1
lapack_opt_info:
    libraries = ['mkl_lapack95', 'mkl_blas95', 'mkl_intel_c', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd', 'mkl_lapack95', 'mkl_blas95', 'mkl_intel_c', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd']
    library_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/lib/ia32']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/include']
blas_opt_info:
    libraries = ['mkl_lapack95', 'mkl_blas95', 'mkl_intel_c', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd']
    library_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/lib/ia32']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_lapack95', 'mkl_blas95', 'mkl_intel_c', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifpo

In [4]:
Z = np.zeros(10)
Z[4] = 1
Z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [5]:
z

NameError: name 'z' is not defined

In [6]:
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
Z = np.arange(9).reshape

In [11]:
z = np.arange(50)
z[::-2]

array([49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17,
       15, 13, 11,  9,  7,  5,  3,  1])

In [12]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
nz

(array([0, 1, 4]),)

In [13]:
z = np.eye(3)
z

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [1]:
import numpy as np

In [2]:
z = np.random.random((3, 3, 3))
z

array([[[ 0.92220713,  0.02851458,  0.31899543],
        [ 0.62350637,  0.72004316,  0.64320354],
        [ 0.33673219,  0.06934428,  0.17295699]],

       [[ 0.90569722,  0.13388949,  0.86493301],
        [ 0.25496932,  0.35910101,  0.06418119],
        [ 0.21491105,  0.24635132,  0.01689869]],

       [[ 0.43123395,  0.78154208,  0.29071058],
        [ 0.31884397,  0.82073414,  0.48536188],
        [ 0.1019654 ,  0.37302868,  0.14435696]]])

In [14]:
z = np.random.random((10, 10))
z

array([[ 0.18977515,  0.57719082,  0.19058963,  0.42183296,  0.46702931,
         0.26999965,  0.72840907,  0.45114308,  0.52602517,  0.95497579],
       [ 0.71332874,  0.7582403 ,  0.59238749,  0.18050166,  0.4956571 ,
         0.44372604,  0.63144166,  0.05538355,  0.58295565,  0.36490517],
       [ 0.01601921,  0.91956444,  0.40914807,  0.92545109,  0.55341394,
         0.90096611,  0.32293195,  0.95763564,  0.56030259,  0.03320138],
       [ 0.56878871,  0.7175878 ,  0.61036959,  0.41308348,  0.63383007,
         0.77011896,  0.73506817,  0.90829685,  0.61533521,  0.24179049],
       [ 0.95169437,  0.38081598,  0.13676149,  0.54913052,  0.7148068 ,
         0.07951351,  0.40306804,  0.77783352,  0.74821484,  0.80455112],
       [ 0.25468173,  0.3141767 ,  0.61413609,  0.99422241,  0.81394595,
         0.17554847,  0.85880889,  0.02126474,  0.03120535,  0.50608691],
       [ 0.43890654,  0.52153134,  0.84884865,  0.65416809,  0.55186314,
         0.25130939,  0.6958044 ,  0.65532794

In [15]:
zmin, zmax = z.min(), z.max()
print(zmin, zmax) 

(0.011338601886222044, 0.99422241312020243)


In [18]:
np.random.random(30)
m = z.mean()
m
# Vector size 30

0.53755348394088809

In [27]:
z = np.ones((5,10))
z[1:-1,1:-1] = 0
z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [29]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [36]:
z = np.diag(1+np.arange(4),k=1)
z

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [42]:
d = np.diag(1+np.arange(4), k=0)
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
d = np.diag(1+np.arange(4), k=-1)
d

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [54]:
z = np.zeros((8,8),dtype=int)
z[1::3,::2] = 1
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [55]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [56]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [57]:
z = np.tile( np.array([[0,2],[1,0]]), (4,4))
z

array([[0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [58]:
np.tile

<function numpy.lib.shape_base.tile>

In [68]:
z = np.tile( np.array([[0,2],[1,0]]), (3,4))
z

array([[0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [70]:
z = np.random.random((5,5))
zmax, zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
z

array([[ 0.98305937,  0.18222752,  0.36151171,  0.41298032,  0.02791064],
       [ 0.63598885,  1.        ,  0.8319816 ,  0.08601212,  0.40362216],
       [ 0.96134967,  0.73474032,  0.88339133,  0.84418479,  0.98219162],
       [ 0.05437988,  0.67650001,  0.38918514,  0.73092938,  0.4496161 ],
       [ 0.86576031,  0.72607498,  0.79664168,  0.        ,  0.75591523]])

In [77]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [80]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [5]:
def generate():
    for x in xrange(10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1) 
print(z)
        

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [87]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])